version: '3.4'

services:
  rabbitmq2:
    image: rabbitmq:3-management
    container_name: "rabbitmq2"
    hostname: rabbitmq2
    ports:
      - "15673:15672"
      - "5673:5672"
    # networks:
    #   default:
    #     name: bridge

# networks:
#   network:
#     driver: bridge
#     ipam:
#       driver: default
#       config:
#         - subnet: 172.20.0.0/16
